### ISSUE TITLE
Bishoujo Senshi Sailor Moon (English patched) fails to boot

### ISSUE THREAD

**Issue by neutralinsomniac** [Mazamars312/openfpga-pcengine-cd#13]
I've tried with both the v3.0 US and Japan BIOS. After hitting Run at the BIOS screen, I get "Just a moment..." then nothing further.

**Comment by kftX** [comment]
> I've tried with both the v3.0 US and Japan BIOS. After hitting Run at the BIOS screen, I get "Just a moment..." then nothing further.

I had this issue earlier, you need to unmerge the bin file. Get [BINmerge](https://github.com/putnam/binmerge) and run the following command in a terminal/command line:

`binmerge.exe --split "name of your sailor moon.cue" "new name for the unmerged file"`

I did this for my copy of Sailor Moon and it worked. Hope this helps!

**Comment by neutralinsomniac** [comment]
That fixed it! Thank you!
