### ISSUE TITLE
Ginga Fukei Densetsu Sapphire Freezes 

### ISSUE THREAD

**Issue by ChrisitanNavas** [Mazamars312/openfpga-pcengine-cd#17]
After selecting the Ginga Fukei Densetsu Sapphire within the common folder than selecting the "[BIOS] TurboGrafx CD Super System Card (USA) (v3.0).pce"  you will get direct to the CD Super System Screen once you press run you get directed to a screen showing the main character. After this happens you can't do anything and the game just get's stuck on this screen. 

Repro Steps
1. Drop down to pcecd rom 
2.  select game "Ginga Fukei Densetsu Sapphire"
3.  Once on the Mazamars312 folder select [BIOS] TurboGrafx CD
4.  On the CD Super System Screen press run 
5.  Game will boot to a screen showing one of the characters and just freeze on the screen.

**Comment by BoscoTheMan82** [comment]
Make sure you're using the newest core version, hit the analog button after loading the bios and pick core settings and scroll down to arcade system and activate that and then reset the core and it will work

**Comment by ChrisitanNavas** [comment]
just tried this and ran into the same issue again.


![20230207_222628](https://user-images.githubusercontent.com/109101247/217443313-641b5e05-4157-4b8c-ba61-8d6b644f266e.jpg)

**Comment by BoscoTheMan82** [comment]
download the core from the sidebar and overwrite the files, there was a file not updated in the original release

**Comment by ifighftdragons** [comment]
This issue can be closed.

It's solved by:
1. Downloading the latest release.
2. Enable Arcade in the core menu.
3. Use the Japanese 3.0 BIOS (This works, perhaps the USA Bios works too)

**Comment by ChrisitanNavas** [comment]
Yes using the method that @BoscoTheMan82 solved the issue and now it's running.

**Comment by ifighftdragons** [comment]
> Yes using the method that @BoscoTheMan82 solved the issue and now it's running.

Glad to hear it's working. Just close the issue.
