### ISSUE TITLE
The core cannot load json stored in multiple levels folders

### ISSUE THREAD

**Issue by mathieulh** [Mazamars312/openfpga-pcengine-cd#20]
The core cannot load json stored in multiple levels folders. 
While it does see the json files, and selecting it does prompt you to select the bios pce files, once you do it does not load the bios and prompt you to load another json file.

This means you currently need the json to be stored in the main asset folder and can't have it stored on sub folders or it won't even attempt to load the BIOS

I am currently using this https://github.com/neil-morrison44/openfpga-instance-packager/releases/tag/v0.3.0 on Windows with the -f argument to generate the json instances.

**Comment by neil-morrison44** [comment]
@mathieulh can you attach the JSON file that's not working? Interested to see if it goes over the 255 character limit anywhere

**Comment by YLFAndy** [comment]
I've got mine in alphabetized folders and they work fine. I generated mine using PocketSync's extension. Interesting that different generators might have different results.

**Comment by mathieulh** [comment]
[PCECD-NonRedump.zip](https://github.com/Mazamars312/openfpga-pcengine-cd/files/10688205/PCECD-NonRedump.zip)
Here are all the json files I have generated, I haven't got to get a single one working

I kept the file tree as is.

**Comment by neil-morrison44** [comment]
I wrote the https://github.com/neil-morrison44/openfpga-instance-packager then just use it internally within Pocket Sync so it should be exactly the same behaviour, it is a version behind though but all that version added was keeping the folder tree from the input in the output

**Comment by neil-morrison44** [comment]
@mathieulh  Ah yeah - think I see what's up

if you change `"datapath": "Unlicensed\\USA\\Revival Chase (USA) (En,Fr) (Unl)/"` -> `"datapath": "Unlicensed/USA/Revival Chase (USA) (En,Fr) (Unl)/"` does it work?

If it does, I recommend closing this issue & opening one on https://github.com/neil-morrison44/openfpga-instance-packager

(it'll be a windows only bug since the Pocket & Mac & Linux use `/` to separate folders)

**Comment by mathieulh** [comment]
Update: Even after writing all the json directly to the main folder it does not seem to work it will not attempt to load the BIOS file (it'll ask for some other file instead once I select the BIOS) I am at a loss as to what's happening, I will attempt to add less games.

**Comment by YLFAndy** [comment]
Just to be clear, you have the JSON files stored in the Assets/pcecd/Mazamars312.PC Engine CD, not in the /common folder with your games, right?

**Comment by mathieulh** [comment]
> Just to be clear, you have the JSON files stored in the Assets/pcecd/Mazamars312.PC Engine CD, not in the /common folder with your games, right?

That is indeed the case.

**Comment by mathieulh** [comment]
I fixed it, I deleted the PC Engine CD core from the SD Card and redownloaded it using pocket updater and the issue is gone.
As I am not quite sure as to what caused this, I am sharing my non working version of the core with its configuration.
I will close this issue.

[Mazamars312.PC Engine CD.zip](https://github.com/Mazamars312/openfpga-pcengine-cd/files/10688365/Mazamars312.PC.Engine.CD.zip)
