### ISSUE TITLE
(Readme issue) JSON manual mode creation's tutorial mistake (didn’t resolve yet)

### ISSUE THREAD

**Issue by MelonGx** [Mazamars312/openfpga-pcengine-cd#25]
> JSON Manual mode creation
> in the assets\pcecd\Mazamars312.PC Engine CD\ folder there a image_template.json file. depending on how many BIN files files is how many dataslots you use and folder location.
> "data_path": "image/", is the folder location in the \Assets\pcecd\common\ folder

I firstly wrote "image/tokimeki/" to direct \Assets\pcecd\common\tokimeki\ , but failed to boot.
Then I modified it to "tokimeki/" to direct \Assets\pcecd\common\tokimeki\ , successfully booted.
So I think the correct data path of "image/" should be \Assets\pcecd\common\image\ but not \Assets\pcecd\common\ , which means the description I quoted is wrong.

**Comment by Mazamars312** [comment]
This was for the json file as you have to write them for this. So the document is correct for that part,

**Comment by MelonGx** [comment]
No I still think your description made me think in that way.

You don’t give me a proper explanation why “image/“ = “assets/pcecd/common” but the fact is “image/“ = “assets/pcecd/common/image/“.

**Comment by NeitherMeNorYou** [comment]
I would personally suggest changing the sentence to help with readability for people that have to rely on machine translation, and don't want to use one of the updaters.

My suggestion would be the following:

"data_path": "image/", replace "image" with the name of the folder that contains the bin+cue files. The folder must be located in \Assets\pcecd\common\

**Comment by MelonGx** [comment]
> My suggestion would be the following:
> 
> "data_path": "image/", replace "image" with the name of the folder that contains the bin+cue files. The folder must be located in \Assets\pcecd\common\

Your explanation is acceptable although I need time to get what you meant.
But the author adopted nothing but still left it wrong.
