### ISSUE TITLE
Taking screenshots delays CD audio and streaming video causing a variety of issues. 

### ISSUE THREAD

**Issue by SpookySquidGames** [Mazamars312/openfpga-pcengine-cd#27]
This is a general issue I've noticed across multiple games, taking screenshots often causes music to stop and then resume a second or two later. The game itself keeps running uninterrupted, so in situations with precisely synced visuals the audio and visuals will end up out of sync. Two good games for testing this are the English fan translations of Galaxy Fraulein Yuna 2 and Madou Monogatari since they both have really well timed subtitles. Weirdly this issue does not seem to effect Galaxy Fraulein Yuna 1, a rare exception. 

In Galaxy Fraulein Yuna 2 boot the game and watch the opening cinematic to see the correct timing. Then reset the core and take a couple screenshots early on during the cutscene using the "analogue button + right system button" shortcut. You'll notice the audio stops briefly each time and then lags behind the visuals and subtitles by a few seconds. It'll also cut off early when it eventually hits a scene change. 

In Madou Monogatari the first voiced cutscene is right after you hit run on the title screen, repeat the process above with it and you'll see the same issue with the audio lagging behind the visuals and subtitles. 

To see a related effect with video streaming off the CD, start up either of the Sherlock Holmes Consulting Detective games and select "Holmes' Introduction" from the title screen. Let the video run for a few lines, then take a screenshot. The video will glitch out a bit, shut down and then restart from the beginning. 

Hope this info is helpful for tracking this down!

**Comment by Mazamars312** [comment]
This is an issue with the APF frame work delaying the access for the image access. This is not something can I can with the delaying. however the restarting Ill look at as it looks like the core is not allowing a delay of data. So maybe even the mister core might have this issue if there is a delay of data.

**Comment by SpookySquidGames** [comment]
Thanks for the explanation! I was afraid this might be on the Analogue side. Is this something that might get fixed in a later version of the APF from Analogue or is that unlikely/impossible? I noticed they really improved the screenshot interruption issues for the non CD based cores with the last Analogue OS update.

**Comment by Mazamars312** [comment]
Dont know. But I recommend using the dock for this sort of things if you want to do a lot of screen grabs
