### ISSUE TITLE
Memory base 128 is not available in A-Train III.

### ISSUE THREAD

**Issue by araitk1130** [Mazamars312/openfpga-pcengine-cd#28]
Unable to save game because "Memory Base 128" is not recognized by A-Train III.
Is "memory base 128" unsupported?

![20220212_094142](https://user-images.githubusercontent.com/28684248/218287258-e7e04ae7-8269-455e-b72d-59d829bb1e11.png)

**Comment by Mazamars312** [comment]
Not at this moment. Will look at this later on
