### ISSUE TITLE
New update causes audio garbled issue on every game now

### ISSUE THREAD

**Issue by manichispanic999** [Mazamars312/openfpga-pcengine-cd#31]
Just manually updated the core and now every game has audio garbled issue and sounds like a helicopter.

**Comment by BooBerry** [comment]
Yep, I'm seeing this too. It looks like, from what I can tell, games are running too fast because the sprites and animations in-game are moving faster than normal.

Downgraded to 0.1.6 and all is well again.

**Comment by manichispanic999** [comment]
> Yep, I'm seeing this too. It looks like, from what I can tell, games are running too fast because the sprites and animations in-game are moving faster than normal in addition to the CDDA audio playing back faster, which comes off as audio skipping (or a helicopter).
> 
> Downgraded to 0.1.6 and all is well again.

I tried fiddling with some of the new audio settings but nothing was working. I downgraded the core as well.

**Comment by manichispanic999** [comment]
I rewrote all the .json files and the audio seems to be better, but it still sounds off. I'll test more later with the Dock when i get home

**Comment by Mazamars312** [comment]
When you say you re-wrote the JSON's what do you mean? as then there is an issues with the updaters here then which we need to report.

**Comment by AC6y86** [comment]
Hitting the same issue, downgrading the core doesn't make a difference.  Was working prior to the update.  Once a game starts when I hit the Analogue button, the UI is reeeallllyyy slow which I'm betting is related.

**Comment by manichispanic999** [comment]
> When you say you re-wrote the JSON's what do you mean? as then there is an issues with the updaters here then which we need to report.

Your core is fine, I had to run the updater and use the "build .json" file setting and overwrote the old .json file and it works fine now.

**Comment by AC6y86** [comment]
Regenerating didn't solve the issue for me.

**Comment by BooBerry** [comment]
Nor for me (and nor did a clean install of the core + deleting settings to start fresh).

**Comment by AC6y86** [comment]
Is it possible to reopen this?  Can’t find the button.
