### ISSUE TITLE
Loom won't boot

### ISSUE THREAD

**Issue by ifighftdragons** [Mazamars312/openfpga-pcengine-cd#41]
Loom won't boot. Just goes to a black screen after BIOS screen.
No problem with any other games.

Anyone having the same problem?

**Comment by davewongillies** [comment]
Loom (USA) from the Redump PC Engine CD collection works for me

**Comment by ifighftdragons** [comment]
> Loom (USA) from the Redump PC Engine CD collection works for me

Just tried it, and the same issue persist. It goes to a black screen after BIOS screen.
All the other games work.

**Comment by ifighftdragons** [comment]
Got it working. Had to enable the setting "System Region" in the core menu. Thanks for the helo dave!
