### ISSUE TITLE
No way to load Ys Book I & II

### ISSUE THREAD

**Issue by MP2E** [Mazamars312/openfpga-pcengine-cd#5]
With split .cue and .bin files, there are over 40 bin files. But also when merging all the bin files with binmerge (https://github.com/putnam/binmerge) the .cue and .bin cannot be loaded, as the Pocket shows "Error in Framework File ID [101] Too Large"

All the other dumps I have seem to work fine and I made sure that I'm using a redump copy

**Comment by neil-morrison44** [comment]
I wonder if a custom binmerge that merges the bins into ~20 instead of 1 would help?

**Comment by Mazamars312** [comment]
What is the total size of the BIN file you make? as there is a 700mbyte limit I have on thos which you can increase to about 4Gbytes if needed.

**Comment by MP2E** [comment]
@Mazamars312  The combined bin file for Ys Book I & II is 768.1MB

**Comment by Mazamars312** [comment]
Ah. Go into the data.json and increase the max size to say 838860800 on dataslot 101. I can add this on the update I'm doing with some other things

**Comment by MP2E** [comment]
Works perfectly! Thank you very much. I didn't realize this was something I could easily change. Still learning the ropes on the Analogue Pocket and reading the developer documentation.

Thank you! I will close this ticket
