### ISSUE TITLE
Versioning::Version info in core.json included in the alpha RAR file is incorrect

### ISSUE THREAD

**Issue by YLFAndy** [Mazamars312/openfpga-pcengine-cd#56]
Feel free to close this, but just in case it wasn't documented. 

The version info on the 0.20.0a release is still set to 0.17.0 and the date is still February in the core json files.

**Comment by mattpannella** [comment]
you still have the 0.17.0 build
https://github.com/Mazamars312/openfpga-pcengine-cd/blob/68f68c9a11a2453e03ef466e890684580b19a712/dist/Cores/Mazamars312.PC%20Engine%20CD/core.json#L10

**Comment by YLFAndy** [comment]
> you still have the 0.17.0 build
> 
> https://github.com/Mazamars312/openfpga-pcengine-cd/blob/68f68c9a11a2453e03ef466e890684580b19a712/dist/Cores/Mazamars312.PC%20Engine%20CD/core.json#L10

I downloaded the precomped rar. I'll check again when I'm back to my computer, but I'm fairly certain it is wrong in the rar.

**Comment by YLFAndy** [comment]
@mattpannella 

<img width="545" alt="image" src="https://github.com/Mazamars312/openfpga-pcengine-cd/assets/115659432/2c09609f-4cc2-4d29-a921-fa181cb799c8">

**Comment by davewongillies** [comment]
@YLFAndy the RAR file has been updated and has the correct version in it now

**Comment by YLFAndy** [comment]
Thanks! Closing the bug!
