### ISSUE TITLE
Madou Monogatari I: Honoo no Sotsuenji getting a "Please play using an Arcade Card" error

### ISSUE THREAD

**Issue by SpookySquidGames** [Mazamars312/openfpga-pcengine-cd#7]
I'm getting a "Please play using an Arcade Card" error when trying to play the English patch of Madou Monogatari I: Honoo no Sotsuenji. I've tested it both with the recommended bios "[BIOS] Super CD-ROM System (Japan) (v3.0).pce" and the US one. I've also tested various Core Settings, turning the Arcade System and System Region settings on and off etc. No combination of bios and core settings seems to fix the issue.

I'm assuming this is an Arcade Card issue, but according to the patch's readme (see the section Running the Game) this error can also appear when the wrong bios is used. https://www.romhacking.net/translations/tgcd/patches/5805readme.txt

Is the Arcade Card not supported yet? I checked and didn't see anything about that in the github readme. Thanks!

**Comment by Mazamars312** [comment]
This bug was just found else where and I just patched it in veriosn 0.1.6 (This only just came out about 10 minutes ago).

**Comment by SpookySquidGames** [comment]
Still getting the error after updating unfortunately. 

BTW it looks like the about screen on the Pocket still lists the new version as 0.1.5.  I deleted my old core files and updated again just to be sure I was actually using 0.1.6.

**Comment by MP2E** [comment]
Works here with the latest version, but note I'm using a bios named: "[BIOS] Super CD-ROM System (Japan) (v3.0).pce" and I also turned on Arcade System in the core settings

**Comment by MP2E** [comment]
Well actually the cutscene for the intro seems to be all black with only audio playing? But it runs other than that..

**Comment by SpookySquidGames** [comment]
Odd. I'm also using "[BIOS] Super CD-ROM System (Japan) (v3.0).pce" with Arcade System on and still getting the error. 
I checked CRC and MD5 for the bios file and it checks out. 
I also tested with an unpatched Japanese copy of the game and am getting the error, but in Japanese. 

MP2E when you check the About readme file on the pocket for the core is it displaying version 0.1.5 or 0.1.6?  My only guess now is that some stray file somewhere has stuck around from the earlier version and it's not correctly updating to 0.1.6 for some reason. 

Anything else that could be causing this I should look into?

**Comment by SpookySquidGames** [comment]
Ok update. I figured out that the Pocket Updater must have been silently decrementing my version back to 0.1.5 when I ran it to build the json files. I went and deleted every file other than the game jsons related to the core that I could find and re-installed 0.1.6 again without running Pocket Updater but it's still giving me the fail message in both versions of the game.  Really at a loss as to what could be causing the issue for me now.

**Comment by MP2E** [comment]
[pce.zip](https://github.com/Mazamars312/openfpga-pcengine-cd/files/10671899/pce.zip)

Here is a copy of the exact core I'm using, copied off my sd card. I did build this from scratch using the latest source, but I don't think it should differ from the actual release. Maybe it'll work though?

**Comment by Mazamars312** [comment]
Ah my release does not have the correct upoload. Let me patch this ASAP. Sorry guys my fault here

**Comment by sudoplay** [comment]
The re-released patch corrected the same arcade card issue in Ginga Fukei Densetsu Sapphire.

**Comment by SpookySquidGames** [comment]
Newest version via Updater did the trick! Thanks so much for the quick fix! 
By the way both Pocket Sync and Pocket Updater still report the new version as 0.1.5, but the actual files are the new ones and run the game. Guessing some stray file still has 0.1.5 written in it or something.

**Comment by Mazamars312** [comment]
Excellent. will close off.
